### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by vcvishal** [Ori-Roza/malaria-cells-classification#1]
sing TensorFlow backend.
Parasitized data
Uninfected data
2000 2000
Traceback (most recent call last):
  File "CNN.py", line 91, in <module>
    nn.train()
  File "CNN.py", line 66, in train
    self.prepare_data(data_dir)
  File "CNN.py", line 53, in prepare_data
    data = np.array(data, dtype="float") / 255.0
ValueError: setting an array element with a sequence.

why this happening?
thank you

**Comment by Ori-Roza** [comment]
hey,
sorry for the delay.

have you put the data correctly?
it seems like the data shape is incorrect.
an example is attached

![Screen Shot 2020-03-12 at 17 45 55](https://user-images.githubusercontent.com/13602756/76539370-5c4bf380-6489-11ea-8404-5df543e7b013.png)
![Screen Shot 2020-03-12 at 17 45 43](https://user-images.githubusercontent.com/13602756/76539375-5d7d2080-6489-11ea-8921-cd500f62182f.png)
